(function(a,c,s){function m(a){for(var b={},d,y,e=0;e<a.length;e++)y=a[e],d=y.r+y.s+y.m,y.c&&(b[d]||(b[d]=[]),b[d].push(a[e]));return b}function o(a){for(var b=1;b<arguments.length;b++){var d=arguments[b];try{if(d.isSupported)return d.send(a)}catch(y){}}}function k(){for(var a=0;a<w.length;a++)w[a]();p.length&&o(m(p.splice(0,p.length)),E,G,C);I=B=0}function n(b,L,d){d=d||{};0===d.bf&&f.isBF||(b={r:d.r||f.rid,s:d.s||a.ue_sid,m:d.m||a.ue_mid,mkt:d.mkt||a.ue_mkt,sn:d.sn||a.ue_sn,c:L,d:b,t:d.t||f.d(),
cs:d.c&&a.ue_qsl},d.b?o(m([b]),E,C):d.nb?o(m([b]),E,G,C):d.img||F[L]?o(m([b]),C):d.n?(p.push(b),0===A?k():I||(I=c.setTimeout(k,A))):(p.push(b),B||(B=c.setTimeout(k,J))))}function r(a,b,d){D++;D==v?n({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},c.ue_err_chan||"jserr"):D<v&&n(a,b,d)}function j(){if(!H){for(var a=0;a<x.length;a++)x[a]();for(a=0;a<w.length;a++)w[a]();o(m(p.splice(0,p.length)),E,C);H=!0}}var h={};(function(){function a(b){return 10>b?"0"+b:b}function b(a){y.lastIndex=
0;return y.test(a)?'"'+a.replace(y,function(a){var b=q[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function d(a,u){var y,q,i,c,g=e,K,h=u[a];h&&"object"===typeof h&&"function"===typeof h.toJSON&&(h=h.toJSON(a));"function"===typeof z&&(h=z.call(u,a,h));switch(typeof h){case "string":return b(h);case "number":return isFinite(h)?String(h):"null";case "boolean":case "null":return String(h);case "object":if(!h)return"null";e+=f;K=[];if("[object Array]"===
Object.prototype.toString.apply(h)){c=h.length;for(y=0;y<c;y+=1)K[y]=d(y,h)||"null";i=0===K.length?"[]":e?"[\n"+e+K.join(",\n"+e)+"\n"+g+"]":"["+K.join(",")+"]";e=g;return i}if(z&&"object"===typeof z)for(c=z.length,y=0;y<c;y+=1)"string"===typeof z[y]&&(q=z[y],(i=d(q,h))&&K.push(b(q)+(e?": ":":")+i));else for(q in h)Object.prototype.hasOwnProperty.call(h,q)&&(i=d(q,h))&&K.push(b(q)+(e?": ":":")+i);i=0===K.length?"{}":e?"{\n"+e+K.join(",\n"+e)+"\n"+g+"}":"{"+K.join(",")+"}";e=g;return i}}"function"!==
typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var y=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,
f,q={"":"\\b","\t":"\\t","\n":"\\n","":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},z;"function"!==typeof h.stringify&&(h.stringify=function(a,b,y){var u;f=e="";if("number"===typeof y)for(u=0;u<y;u+=1)f+=" ";else"string"===typeof y&&(f=y);if((z=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return d("",{"":a})})})();var g=function(){function a(b,d){if(null==b)return d.push("!n");if("number"===typeof b)return d.push("!"+b);if("string"===typeof b)return"\\"==
b[b.length-1]?d.push("'"+b.replace(/'/g,"\\'")+"u005C'"):d.push("'"+b.replace(/'/g,"\\'")+"'");if("boolean"===typeof b)return d.push(b?"!t":"!f");if(b instanceof Array){d.push("*");for(var y=0;y<b.length;y++)a(b[y],d);return d.push(")")}if("object"==typeof b){d.push("(");for(y in b)b.hasOwnProperty(y)&&(d.push(y),a(b[y],d));return d.push(")")}return d.push("!n")}return{stringify:function(b){var d=[];a(b,d);return d.join("")}}}(),l=a.ue_qsl||2E3,v=1E3,t=function(){},b="",q=c.JSON&&c.JSON.stringify||
h&&h.stringify,e=g.stringify,f=a.ue||{},g=a.uet||t;(a.uet||t)("bb","ue_frst_v2",{wb:1});var i="//"+a.ue_furl+"/1/batch/1/OE/",p=[],x=[],w=[],H=!1,I,B,A=void 0===a.ue_hpfi?1E3:a.ue_hpfi,J=void 0===a.ue_lpfi?1E4:a.ue_lpfi,F={"scheduled-delivery":1},D=0,G=function(){function u(){if(c.XDomainRequest){var a=new XDomainRequest;a.onerror=t;a.ontimeout=t;a.onprogress=t;a.onload=t;a.timeout=0;return a}if(c.XMLHttpRequest){a=new XMLHttpRequest;if(!("withCredentials"in a))throw b;return a}if(c.ActiveXObject){for(var u=
0;u<d.length&&!a;u++)try{a=new ActiveXObject(d[u]),d=[d[u]]}catch(e){}return a}}function e(b){for(var d=[],u=b[0]||{},L=0;L<b.length;L++){var z={};z[b[L].c]=b[L].d;d.push(z)}return{rid:u.r||f.rid,sid:u.s||a.ue_sid,mid:u.m||a.ue_mid,mkt:u.mkt||a.ue_mkt,sn:u.sn||a.ue_sn,reqs:d}}var d="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");return{send:function(a){for(var d in a)if(a.hasOwnProperty(d)&&a[d].length){var f=e(a[d]),c=u();
if(!c)throw b;c.open("POST",i,!0);c.setRequestHeader&&c.setRequestHeader("Content-type","text/plain");c.send(q(f))}},buildPOSTBodyLog:e,isSupported:!0}}(),C=function(){return{send:function(b){for(var L in b)if(b.hasOwnProperty(L)){for(var d=b[L],y=d,Q={},c=void 0,h=0;h<y.length;h++)c=y[h].c,Q[c]||(Q[c]=[]),Q[c].push(y[h]);var d=d[0]||{},y=d.sn||a.ue_sn,d=i+(d.m||a.ue_mid)+":"+(d.s||a.ue_sid)+":"+(d.r||f.rid)+(y?":"+y:""),y=[],c=d,h=[],z=void 0;for(z in Q)if(Q.hasOwnProperty(z))for(var N=0;N<Q[z].length;N++){var g=
Q[z][N],R=encodeURIComponent((g.cs?e:q)(g.d));h.push({l:R,t:g.t,p:1,c:z,d:g.cs?"c":"j"})}Q=h;h=void 0;z="$";for(g=0;g<Q.length;){N=Q[g];h!=N.c?(c+=z+N.c+"=",z="&",h=N.c):c+=",";var R=c,j=N.d+":",p=N,c=(p.l.match(".{1,"+(l-c.length)+"}[^%]{0,2}")||[])[0]||"";p.l=p.l.substr(c.length);c=R+(j+c+":"+N.t);if(N.l)c+=":"+N.p++ +"_",y.push(c),c=d,z="$",h=0;else if(g++,1!=N.p)for(c+=":"+N.p+"_"+N.p,R=0;R<N.p-1;R++)y[y.length-R-1]+=N.p}y.push(c);d=y;for(y=0;y<d.length;y++)(new Image).src=d[y]}},isSupported:!0}}(),
E=function(){return{send:function(a){for(var e in a)if(a.hasOwnProperty(e)){var d=G.buildPOSTBodyLog(a[e]);if(!navigator.sendBeacon(i,q(d)))throw b;}},isSupported:!!navigator.sendBeacon}}();f._fic=C;f._fac=G;f._fbc=E;f._flq=p;f.sid=f.sid||a.ue_sid;f.mid=f.mid||a.ue_mid;f.furl=f.furl||a.ue_furl;f.sn=f.sn||a.ue_sn;f.isBF=function(){var a=c.performance||c.webkitPerformance,b=s.ue_backdetect&&s.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,d=f.bfini;return a&&a.navigation&&2===a.navigation.type||
1<d||!d&&1<b}();try{c.amznJQ&&c.amznJQ.declareAvailable&&c.amznJQ.declareAvailable("forester-client"),c.P&&c.P.register&&c.P.register("forester-client",t)}catch(P){a.ueLogError(P,{logLevel:"WARN"})}(function(){f.log&&f.log.isStub&&(f.log.replay(function(a,b,d){var e=a[2]||{};e.t=b;e.r=d;e.n=1;r(a[0],a[1],e)}),f.onunload.replay(function(a){x.push(a[0])}),f.onflush.replay(function(a){w.push(a[0])}))})();f.log=r;f.log.reset=function(){D=0};f.onunload=function(a){x.push(a)};f.onflush=function(a){w.push(a)};
f.attach("beforeunload",j);f.attach("pagehide",j);g("ld","ue_frst_v2",{wb:1})})(ue_csm,window,document);
(function(a,c){function s(a){if(a)return a.replace(/^\s+|\s+$/g,"")}function m(b,q){if(!b)return{};b.m&&b.m.message&&(b=b.m);var e=q.m||q.message||"",e=b.m&&b.m.message?e+b.m.message:b.m&&b.m.target&&b.m.target.tagName?e+("Error handler invoked by "+b.m.target.tagName+" tag"):b.m?e+b.m:b.message?e+b.message:e+"Unknown error",e={m:e,f:b.f||b.sourceURL||b.fileName||b.filename||b.m&&b.m.target&&b.m.target.src,l:b.l||b.line||b.lineno||b.lineNumber,c:b.c?""+b.c:b.c,s:[],t:a.ue.d(),name:b.name,type:b.type,
csm:h+" "+(b.fromOnError?"onerror":"ueLogError")},f,c,p=0,n=0,k;f=b.stack||(b.err?b.err.stack:"");e.pageURL=q.pageURL||""+(window.location?window.location.href:"")||"missing";e.logLevel=q.logLevel||j;if(c=q.attribution)e.attribution=""+c;if(f&&f.split)for(e.csm+=" stack",c=f.split("\n");p<c.length&&e.s.length<g;)(f=c[p++])&&e.s.push(s(f));else for(e.csm+=" callee",c=o(b.args||arguments,"callee"),n=p=0;c&&p<g;)k=l,c.skipTrace||(f=c.toString())&&f.substr&&(k=0===n?4*l:k,k=1==n?2*l:k,e.s.push(f.substr(0,
k)),n++),c=o(c,"caller"),p++;if(!e.f&&0<e.s.length&&(p=e)&&p.s){var m;f=0<p.s.length?p.s[0]:"";c=1<p.s.length?p.s[1]:"";f&&(m=f.match(t));m&&3==m.length||!c||(m=c.match(v));m&&3==m.length&&(p.f=m[1],p.l=m[2])}return e}function o(a,q){try{return a[q]}catch(e){}}function k(b,q){if(b){var e=m(b,q);a.ue.log(e,q.channel||r,{nb:1});try{var f=c.console,i=c.JSON,h="Error logged: ";if(f){if(i&&i.stringify)try{h+=i.stringify(e)}catch(g){h+="no info provided; converting to string failed"}else h+=e.m;"function"===
typeof f.error?f.error(h,e):"function"===typeof f.log&&f.log(h,e)}}catch(l){}}}function n(b,q){if(b&&!(a.ue_err.ec>a.ue_err.mxe)){a.ue_err.ec++;a.ue_err.ter.push(b);var q=q||{},e=b.logLevel||q.logLevel;q.logLevel=e;q.attribution=b.attribution||q.attribution;e&&e!=j||ue_err.ecf++;k(b,q)}}if(!a.ueLogError||a.ueLogError.isStub){var r=a.ue_err_chan||"jserr",j="FATAL",h="v5",g=20,l=256,v=/\(?([^\s]*):(\d+):\d+\)?/,t=/.*@(.*):(\d*)/;k.skipTrace=1;m.skipTrace=1;n.skipTrace=1;(function(){if(a.ue_err.erl){var b=
a.ue_err.erl.length,q,e;for(q=0;q<b;q++)e=a.ue_err.erl[q],k(e.ex,e.info);ue_err.erl=[]}})();a.ueLogError=n}})(ue_csm,window);
(function(a,c){a.ue_cel||(a.ue_cel=function(){function s(a,q){q?q.r=v:q={r:v,c:1};q.clog&&h.clog?h.clog(a,q.ns||r,q):q.glog&&h.glog?h.glog(a,q.ns||r,q):h.log(a,q.ns||r,q)}function m(){var a=k.length;if(0<a){for(var q=[],e=0;e<a;e++){var f=k[e].api;f.ready()?(f.on({ts:h.d,ns:r}),n.push(k[e]),s({k:"mso",n:k[e].name,t:h.d()})):q.push(k[e])}k=q}}function o(){if(!o.executed){for(var a=0;a<n.length;a++)n[a].api.off&&n[a].api.off({ts:h.d,ns:r});s({k:"eod",t0:h.t0,t:h.d()},{c:1});o.executed=1;for(a=0;a<n.length;a++)k.push(n[a]);
n=[];clearTimeout(j)}}var k=[],n=[],r=a.ue_cel_ns||"cel",j,h=a.ue,g=a.uet,l=a.uex,v=h.rid,t=c.requestAnimationFrame||function(a){a()};if(h.isBF)s({k:"bft",t:h.d()});else return"function"==typeof g&&g("bb","csmCELLSframework",{wb:1}),setTimeout(m,0),h.onunload(o),j=setTimeout(o,6E5),"function"==typeof l&&l("ld","csmCELLSframework",{wb:1}),{registerModule:function(a,q){k.push({name:a,api:q});s({k:"mrg",n:a,t:h.d()});m()},reset:function(a){s({k:"rst",t0:h.t0,t:h.d()});k=k.concat(n);n=[];for(var q=k.length,
e=0;e<q;e++)k[e].api.off(),k[e].api.reset();v=a||h.rid;m();clearTimeout(j);j=setTimeout(o,6E5);o.executed=0},timeout:function(a,q){return c.setTimeout(function(){t(a)},q)},log:s}}())})(ue_csm,window);
(function(a,c,s){a.ue_pdm||ue.isBF||(a.ue_pdm=function(){function m(){var b={w:n.width,aw:n.availWidth,h:n.height,ah:n.availHeight,cd:n.colorDepth,pd:n.pixelDepth},f={w:s.body.scrollWidth,h:s.body.scrollHeight};g&&g.w==b.w&&g.h==b.h&&g.aw==b.aw&&g.ah==b.ah&&g.pd==b.pd&&g.cd==b.cd||(g=b,g.t=j(),g.k="sci",t(g));l&&l.w==f.w&&l.h==f.h||(l=f,l.t=j(),l.k="doi",t(l));r=a.ue_cel.timeout(m,h)}function o(){t({k:"ebl",t:j()})}function k(){t({k:"efo",t:j()})}var n,r,j,h,g,l,v=a.ue,t=a.ue_cel.log,b=a.uet,q=a.uex;
"function"==typeof b&&b("bb","csmCELLSpdm",{wb:1});return{on:function(b){h=b.timespan||500;j=b.ts;n=c.screen;v.attach&&(v.attach("blur",o,c),v.attach("focus",k,c));b=c.location;t({k:"pmd",o:b.origin,p:b.pathname,t:j()});a.ue_cel.timeout(m,0);"function"==typeof q&&q("ld","csmCELLSpdm",{wb:1})},off:function(){clearTimeout(r);v.detach&&(v.detach("blur",o,c),v.detach("focus",k,c));v.count&&(v.count("cel.PDM.TotalExecutions",0),v.count("cel.PDM.TotalExecutionTime",0),v.count("cel.PDM.AverageExecutionTime",
0/0))},ready:function(){return s.body&&a.ue_cel&&a.ue_cel.log},reset:function(){g=l=null}}}(),a.ue_cel&&a.ue_cel.registerModule("page module",a.ue_pdm))})(ue_csm,window,document);
(function(a,c){a.ue_vpm||ue.isBF||(a.ue_vpm=function(){function s(){var a=r(),b={w:c.innerWidth,h:c.innerHeight,x:c.pageXOffset,y:c.pageYOffset};o&&o.w==b.w&&o.h==b.h&&o.x==b.x&&o.y==b.y||(b.t=a,b.k="vpi",o=b,l(o,{clog:1}));k=0;j=r()-a;h+=1}function m(){k||(k=a.ue_cel.timeout(s,n))}var o,k,n,r,j=0,h=0,g=a.ue,l=a.ue_cel.log,v=a.uet,t=a.uex,b=g.attach,q=g.detach;"function"==typeof v&&v("bb","csmCELLSvpm",{wb:1});return{on:function(e){r=e.ts;n=e.timespan||100;a.ue_cel.timeout(s,0);b&&(b("scroll",m),
b("resize",m));"function"==typeof t&&t("ld","csmCELLSvpm",{wb:1})},off:function(){clearTimeout(k);q&&(q("scroll",m),q("resize",m));g.count&&(g.count("cel.VPI.TotalExecutions",h),g.count("cel.VPI.TotalExecutionTime",j),g.count("cel.VPI.AverageExecutionTime",j/h))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){o=void 0},getVpi:function(){return o}}}(),a.ue_cel&&a.ue_cel.registerModule("viewport module",a.ue_vpm))})(ue_csm,window);
(function(a,c,s){var m=a.ue||{};!m.isBF&&!a.ue_fem&&s.querySelector&&c.getComputedStyle&&[].forEach&&(a.ue_fem=a.ue_bwd?function(){function o(a,b,d){var e;a:{try{if(a){var u=a.getBoundingClientRect();e={x:u.left+d.x|0,y:u.top+d.y|0,w:u.width|0,h:u.height|0,d:(0===a.offsetWidth&&0===a.offsetHeight)|0}}else e=void 0;break a}catch(y){}e=void 0}if(e&&!a.cel_b)a.cel_b=e,f({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:b,k:"ewi",cl:a.className},{clog:1});else{if(d=e)d=a.cel_b,
u=e,d=u.d===d.d&&1===u.d?!1:!((d.x>u.x?3>d.x-u.x:3>u.x-d.x)&&(d.y>u.y?3>d.y-u.y:3>u.y-d.y)&&(d.w>u.w?3>d.w-u.w:3>u.w-d.w)&&(d.h>u.h?3>d.h-u.h:3>u.h-d.h)&&d.d===u.d);d&&(a.cel_b=e,f({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:b,k:"ewi"},{clog:1}))}}function k(a,b,d){var u;u=a.c?s.getElementsByClassName(a.c):a.id?[s.getElementById(a.id)]:s.querySelectorAll(a.s);a.w=[];for(widgetIndex=0;widgetIndex<u.length;widgetIndex++){var L=u[widgetIndex];L&&(L.cel_n||(L.cel_n=L.getAttribute("cel_widget_id")||
(a.id_gen||e)(L,widgetIndex)||L.id),a.w.push(L),j(y,L,b,d))}}function n(a,b){i.contains(a)||f({n:a.cel_n,t:b,k:"ewd"},{clog:1})}function r(a){E.length&&ue_cel.timeout(function(){for(var b=O(),d=!1;O()-b<t&&!d;){for(d=u;0<d--&&0<E.length;){var e=E.shift();Q[e.type](e.elem,e.time,e.pageOffset)}d=0===E.length}P++;r(a)},0)}function j(a,b,d,u){E.push({type:a,elem:b,time:d,pageOffset:u})}function h(a,b,d){for(var u=0;u<q.length;u++)for(var e=q[u].w||[],y=0;y<e.length;y++)j(a,e[y],b,d)}function g(){C||(C=
a.ue_cel.timeout(function(){C=null;var a={x:c.pageXOffset,y:c.pageYOffset},u=b();h(L,u);for(var e=0;e<q.length;e++)j(d,q[e],u,a);r(u)},v))}function l(){C||G||(G=a.ue_cel.timeout(function(){G=null;var a={x:c.pageXOffset,y:c.pageYOffset},d=b();h(y,d,a);r(d)},v))}var v=50,t=4.5,b,q=[],e=function(){},f=a.ue_cel.log,i,p,x,w,H=c.MutationObserver||c.WebKitMutationObserver||c.MozMutationObserver,I=!!H,B,A,J="DOMAttrModified",F="DOMNodeInserted",D="DOMNodeRemoved",G,C,E=[],P=0,u=null,L="removedWidget",d="updateWidgets",
y="processWidget",Q,M=c.performance||{},O=M.now&&function(){return M.now()}||function(){return Date.now()};"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(d){function e(){if(x&&w&&i&&i.contains&&i.getBoundingClientRect&&b){Q={removedWidget:n,updateWidgets:k,processWidget:o};if(I){var a={attributes:!0,subtree:!0};B=new H(l);A=new H(g);B.observe(i,a);A.observe(i,{childList:!0,subtree:!0});A.observe(p,a)}else x.call(i,J,l),x.call(i,F,g),x.call(i,D,g),x.call(p,F,l),x.call(p,
D,l);g()}}i=s.body;p=s.head;x=i.addEventListener;w=i.removeEventListener;b=d.ts;q=a.cel_widgets||[];u=d.bs||5;m.deffered?e():m.attach&&m.attach("load",e);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){x&&w&&i&&i.contains&&i.getBoundingClientRect&&b&&(A&&(A.disconnect(),A=null),B&&(B.disconnect(),B=null),w.call(i,J,l),w.call(i,F,g),w.call(i,D,g),w.call(p,F,l),w.call(p,D,l));m.count&&m.count("cel.widgets.batchesProcessed",P)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){q=
a.cel_widgets||[]}}}():function(){function o(){a.ue_cel.timeout(function(){e.splice(0).forEach(function(a){f(a,{clog:1})})},0)}function k(a){for(var u={x:c.pageXOffset,y:c.pageYOffset},L=0;L<b.length;L++){var d=b[L];if(d.w&&d.w.length)for(var y=0;y<d.w.length;y++){var f=d.w[y],q;a:{try{var i=f,z=u;if(i){var h=i.getBoundingClientRect();q={x:h.left+z.x|0,y:h.top+z.y|0,w:h.width|0,h:h.height|0,d:(0===i.offsetWidth&&0===i.offsetHeight)|0}}else q=void 0;break a}catch(g){}q=void 0}if(q&&!f.cel_b)f.cel_b=
q,e.push({n:f.cel_n,w:f.cel_b.w,h:f.cel_b.h,d:f.cel_b.d,x:f.cel_b.x,y:f.cel_b.y,t:a,k:"ewi",cl:f.className});else{if(i=q)i=f.cel_b,z=q,i=z.d===i.d&&1===z.d?!1:!((i.x>z.x?3>i.x-z.x:3>z.x-i.x)&&(i.y>z.y?3>i.y-z.y:3>z.y-i.y)&&(i.w>z.w?3>i.w-z.w:3>z.w-i.w)&&(i.h>z.h?3>i.h-z.h:3>z.h-i.h)&&i.d===z.d);i&&(f.cel_b=q,e.push({n:f.cel_n,w:f.cel_b.w,h:f.cel_b.h,d:f.cel_b.d,x:f.cel_b.x,y:f.cel_b.y,t:a,k:"ewi"}))}}}}function n(a){for(var u=0;u<b.length;u++){var L=b[u],d;d=L;d=d.c?s.getElementsByClassName(d.c):
d.id?[s.getElementById(d.id)]:s.querySelectorAll(d.s);var y=L.w||[],f;for(f=0;f<y.length;f++){var c=y[f];i.contains(c)||e.push({n:c.cel_n,t:a,k:"ewd"})}L.w=[];for(f=0;f<d.length;f++)if(y=d[f])y.cel_n||(y.cel_n=y.getAttribute("cel_widget_id")||(L.id_gen||q)(y,f)||y.id),L.w.push(y)}j()}function r(){C||(C=a.ue_cel.timeout(function(){C=null;h("dwe",n);o()},g))}function j(){C||G||(G=a.ue_cel.timeout(function(){G=null;h("dwpc",k);o()},g))}function h(a,b){var L=t();b(L);var d=t(),L=d-L;L<=l?d=0:d-E>=v?(E=
d,d=0):(ue_fem.off(),d=1);(e.length||d)&&e.push({k:"ewt",e:a,d:L,ex:d,t:t()})}var g=50,l=10,v=3E3,t,b=[],q=function(){},e=[],f=a.ue_cel.log,i,p,x,w,H=c.MutationObserver||c.WebKitMutationObserver||c.MozMutationObserver,I=!!H,B,A,J="DOMAttrModified",F="DOMNodeInserted",D="DOMNodeRemoved",G,C,E=-v;"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(e){function u(){if(x&&w&&i&&i.contains&&i.getBoundingClientRect&&t){if(I){var a={attributes:!0,subtree:!0};B=new H(j);A=new H(r);B.observe(i,
a);A.observe(i,{childList:!0,subtree:!0});A.observe(p,a)}else x.call(i,J,j),x.call(i,F,r),x.call(i,D,r),x.call(p,F,j),x.call(p,D,j);r()}}i=s.body;p=s.head;x=i.addEventListener;w=i.removeEventListener;t=e.ts;b=a.cel_widgets||[];m.deffered?u():m.attach&&m.attach("load",u);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){x&&w&&i&&i.contains&&i.getBoundingClientRect&&t&&(A&&(A.disconnect(),A=null),B&&(B.disconnect(),B=null),w.call(i,J,j),w.call(i,F,r),w.call(i,D,r),w.call(p,F,j),
w.call(p,D,j))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){b=a.cel_widgets||[]}}}(),a.ue_cel&&a.ue_fem&&a.ue_cel.registerModule("features module",a.ue_fem))})(ue_csm,window,document);
(function(a,c){a.ue_mcm||a.ue.isBF||(a.ue_mcm=function(){function s(a){if(a.id)return"//*[@id='"+a.id+"']";var c;c=1;var l;for(l=a.previousSibling;l;l=l.previousSibling)l.nodeName==a.nodeName&&(c+=1);l=a.nodeName;1!=c&&(l+="["+c+"]");a.parentNode&&(l=s(a.parentNode)+"/"+l);return l}function m(a){var g=a.srcElement||a.target||{},l={k:o,w:c.body.scrollWidth,h:c.body.scrollHeight,t:k(),x:a.pageX,y:a.pageY,p:s(g),n:g.nodeName,e:j};a.button&&(l.b=a.button);g.href&&(l.r=g.href);g.id&&(l.i=g.id);g.className&&
(l.c=g.className.split(/\s+/));r(l,{c:1})}var o="mcm",k,n=a.ue,r=a.ue_cel.log,j=a.ue_mce||"click";return{on:function(a){k=a.ts;n.attach&&n.attach(j,m,c)},off:function(){n.detach&&n.detach(j,m,c)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){}}}(),a.ue_cel&&a.ue_cel.registerModule("mouse click module",a.ue_mcm))})(ue_csm,document);
(function(a,c){a.ue_mmm||a.ue.isBF||(a.ue_mmm=function(s){function m(a,b){var e={x:a.pageX||a.x||0,y:a.pageY||a.y||0,t:h()};!b&&I&&(e.t-I.t<n||e.x==I.x&&e.y==I.y)||(I=e,x.push(e))}function o(){if(x.length){i=F.now();for(var a=0;a<x.length;a++){var c=x[a],h=a;B=x[H];A=c;var g=void 0;if(!(g=2>h)){a:if(x[h].t-x[h-1].t>k)g=0;else{for(g=H+1;g<h;g++){var l=B,u=A,L=x[g];J=(u.x-l.x)*(l.y-L.y)-(l.x-L.x)*(u.y-l.y);if(J*J/((u.x-l.x)*(u.x-l.x)+(u.y-l.y)*(u.y-l.y))>r){g=0;break a}}g=1}g=!g}g?H=h-1:w.pop();w.push(c)}p=
F.now()-i;b=Math.min(b,p);q=Math.max(q,p);e=(e*f+p)/(f+1);f+=1;v({k:j,e:w,min:Math.floor(1E3*b),max:Math.floor(1E3*q),avg:Math.floor(1E3*e)},{c:1});x=[];w=[];H=0}}var k=100,n=20,r=25,j="mmm1",h,g,l=a.ue,v=a.ue_cel.log,t,b=1E3,q=0,e=0,f=0,i,p,x=[],w=[],H=0,I,B,A,J,F=s&&s.now&&s||Date.now&&Date||{now:function(){return(new Date).getTime()}};return{on:function(a){h=a.ts;g=a.ns;l.attach&&l.attach("mousemove",m,c);t=setInterval(o,3E3)},off:function(){g&&(I&&m(I,!0),o());clearInterval(t);l.detach&&l.detach("mousemove",
m,c)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){x=[];w=[];H=0;I=null}}}(window.performance),a.ue_cel&&a.ue_cel.registerModule("mouse move module",a.ue_mmm))})(ue_csm,document);